#!/bin/bash

. "global.sh"

say "${cyan}Welcome to my shell setup.${clear}"
sleep 1
say "The script will check if the necessary packages are installed"

check_command(){
  # the command to check
  command=$1
  # some commands can't be installed directly, if that's the case it is possible to specify what to install. Defaults to the command itself
  package=${2:-$1}

  if ! command -v $command &> /dev/null
  then
    say "$command is not installed. Do you want to install it now? [Y/n]"
    read response
    if [[ "${response}" == @(""|"y"|"Y") ]]; then
      say "Installing $command..."
      brew install $command
    else
      say "Not installing. The script will stop"
      exit
    fi
  #else
  # say "$command already installed"
  fi
}

check_command git
check_command gum